output "network_id" {
  description = "ID of the private network generated by the module"
  value       = module.network.network_id
}

output "network_name" {
  description = "Name of the private network generated by the module"
  value       = module.network.network_name
}

output "subnet_ids" {
  description = "Map of regions and their subnet IDs generated by the module"
  value       = module.network.subnet_ids
}

output "ovh_vpn_gateway_public_ip" {
  description = "Brug denne IP-adresse i din Azure Local Network Gateway"
  value       = openstack_networking_floatingip_v2.fip.address
}
