output "network_id" {
  description = "ID of the private network generated by the module"
  value       = module.network.network_id
}

output "network_name" {
  description = "Name of the private network generated by the module"
  value       = module.network.network_name
}

output "subnet_ids" {
  description = "Map of regions and their subnet IDs generated by the module"
  value       = module.network.subnet_ids
}

output "vpn_public_ip" {
  description = "Den offentlige Floating IP-adresse oprettet i OVH"
  value       = openstack_networking_floatingip_v2.fip.address
}