output "network_id" {
  description = "ID of the private network generated by the module"
  value       = module.network.network_id
}

output "network_name" {
  description = "Name of the private network generated by the module"
  value       = module.network.network_name
}

output "subnet_ids" {
  description = "Map of regions and their subnet IDs generated by the module"
  value       = module.network.subnet_ids
}

output "registry_url" {
  value       = module.container_registry.registry_url
  description = "The public URL endpoint of the provisioned Container Registry"
}

output "user" {
  value       = module.container_registry.user
  description = "The generated user used for authenticating against the registry"
}

output "password" {
  value       = module.container_registry.user.password
  sensitive   = true
  description = "The generated password used for authenticating against the registry (Marked Sensitive)"
}